meta:
  environment: ~

update:
  canaries: 1
  max_in_flight: 50
  canary_watch_time: 1000-30000
  update_watch_time: 1000-30000
  serial: false

jobs:
  - name: influxdb_leader_z1
    template: influxdb
    instances: 0
    resource_pool: small_z1
    networks: (( merge ))
    persistent_disk: 0
    properties:
      influxdb:
        cluster:
          is_leader: true
  - name: influxdb_z1
    template: influxdb
    instances: 0
    resource_pool: small_z1
    networks: (( merge ))
    persistent_disk: 0
    update:
      canaries: 10
    properties:
      influxdb:
        cluster:
          leader_address: (( merge ))

networks: (( merge ))

properties: {}
